from django.urls import path
from .views import (
    main_view,
    local_rental_view,
    one_way_view,
    round_trip_view,
    road_trip_view,
    local_transfer_view,
    enquiry_view,
    chatbot_view,
    city_detail,
    all_cities,
    city_autocomplete,
    taxi_list,
    booking_detail_view,
    booking_confirmation,
    submit_rating,
    about_us,
    privacy_policy,
    terms_and_conditions,
    careers
)

urlpatterns = [
    path('', main_view, name='main'),
    path('local-rental/', local_rental_view, name='local_rental'),
    path('one-way/', one_way_view, name='one_way'),
    path('round-trip/', round_trip_view, name='round_trip'),
    path('road-trip/', road_trip_view, name='road_trip'),
    path('local-transfer/', local_transfer_view, name='local_transfer'),
    path('enquiry/', enquiry_view, name='enquiry'),
    path('chatbot/', chatbot_view, name='chatbot_view'), 
    path('city/<slug:slug>/', city_detail, name='city_detail'),
    path('all-cities/', all_cities, name='all_cities'),
    path('autocomplete/', city_autocomplete, name='city_autocomplete'),
    path('taxi', taxi_list, name='taxi-list'),
    path('<int:booking_id>/book/', booking_detail_view, name='booking-detail'),
    path('booking/confirmation/<int:booking_id>/', booking_confirmation, name='booking_confirmation'),
    path('booking/rating/<int:booking_id>/', submit_rating, name='submit_rating'),
    path('about/', about_us, name='about'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    path('terms-and-conditions/', terms_and_conditions, name='terms_and_conditions'),
    path('careers/', careers, name='careers'),
]
