# Generated by Django 5.2.4 on 2025-07-23 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("pickup_city", models.CharField(max_length=100)),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Mini", "Mini"),
                            ("Luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("travellers", models.PositiveIntegerField()),
                ("pickup_date", models.DateField()),
                ("drop_date", models.DateField()),
                ("trip_details", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
