# Generated by Django 5.2.4 on 2025-07-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_city", models.CharField(max_length=100)),
                (
                    "ride_type",
                    models.CharField(
                        choices=[
                            ("Local Rental", "Local Rental"),
                            ("One Way", "One Way"),
                            ("Round Trip", "Round Trip"),
                            ("Road Trip", "Road Trip"),
                            ("Local Transfer", "Local Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pickup_datetime", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
