# Generated by Django 5.2.4 on 2025-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_ridesearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("Mini Ride - 4h/40km", "Mini Ride - 4h/40km"),
                            ("Half Day - 8h/80km", "Half Day - 8h/80km"),
                            ("Full Day - 12h/120km", "Full Day - 12h/120km"),
                            ("Custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pickup_datetime", models.DateTimeField()),
            ],
        ),
    ]
