# Generated by Django 5.2.4 on 2025-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_localrental"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneWay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("pickup_datetime", models.DateTimeField()),
            ],
        ),
    ]
