# Generated by Django 5.2.4 on 2025-07-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_oneway"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_city", models.CharField(max_length=100)),
                ("pickup_datetime", models.DateTimeField()),
                ("return_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_city", models.CharField(max_length=100)),
                (
                    "round_trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="main.roundtrip",
                    ),
                ),
            ],
        ),
    ]
