# Generated by Django 5.2.4 on 2025-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_roundtrip_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadTripBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=200)),
                ("start_datetime", models.DateTimeField()),
            ],
        ),
    ]
