# Generated by Django 5.2.4 on 2025-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_roadtripbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_city", models.CharField(max_length=100)),
                ("drop_location", models.CharField(max_length=100)),
                ("pickup_time", models.DateTimeField()),
            ],
        ),
    ]
