# Generated by Django 5.2.4 on 2025-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_localtransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("banner_image", models.ImageField(upload_to="city_banners/")),
                ("thumbnail_image", models.ImageField(upload_to="city_thumbnails/")),
                (
                    "content",
                    models.TextField(
                        help_text="Use HTML for formatting the city page content"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
