# Generated by Django 5.2.4 on 2025-07-26 15:01

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_citypage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citypage",
            options={
                "ordering": ["name"],
                "verbose_name": "City Page",
                "verbose_name_plural": "City Pages",
            },
        ),
        migrations.RemoveField(
            model_name="citypage",
            name="banner_image",
        ),
        migrations.RemoveField(
            model_name="citypage",
            name="content",
        ),
        migrations.AddField(
            model_name="citypage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="citypage",
            name="show_on_pages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("home", "Home Page"),
                    ("local", "Local Rental"),
                    ("one_way", "One Way"),
                    ("round_trip", "Round Trip"),
                    ("road_trip", "Road Trip"),
                    ("local_transfer", "Local Transfer"),
                ],
                max_length=54,
            ),
        ),
    ]
