# Generated by Django 5.2.4 on 2025-07-26 18:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_citypage_options_remove_citypage_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypage",
            name="show_on_pages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("home", "Home Page"),
                    ("local_rental", "Local Rental"),
                    ("one_way", "One Way"),
                    ("round_trip", "Round Trip"),
                    ("road_trip", "Road Trip"),
                    ("local_transfer", "Local Transfer"),
                ],
                max_length=61,
            ),
        ),
    ]
