# Generated by Django 5.2.4 on 2025-07-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_citypage_show_on_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxiFare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("local", "8Hrs/80Kms"),
                            ("outstation", "Outstation"),
                            ("oneway", "Outstation Oneway"),
                        ],
                        max_length=20,
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("fare_amount", models.CharField(max_length=50)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxi_fares",
                        to="main.citypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxi Fare",
                "verbose_name_plural": "Taxi Fares",
                "ordering": ["category", "car_name"],
            },
        ),
    ]
