# Generated by Django 5.2.4 on 2025-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_taxifare"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("car_type", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="cars/")),
                ("package_info", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source_city", models.CharField(max_length=100)),
            ],
        ),
    ]
