# Generated by Django 5.2.4 on 2025-07-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxi_name", models.CharField(max_length=100)),
                ("trip_location", models.CharField(max_length=255)),
                ("package_name", models.CharField(max_length=100)),
                ("pickup_datetime", models.DateTimeField()),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Taxi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "car_type",
                    models.CharField(
                        choices=[("SEDAN", "Sedan AC"), ("SUV", "SUV AC")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_info", models.CharField(max_length=100)),
                ("charge_info", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="taxi_images/")),
                ("included_gst", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("pickup_location", models.CharField(max_length=255)),
                ("pay_later", models.BooleanField(default=False)),
                ("accepted_terms", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="main.bookingdetail",
                    ),
                ),
            ],
        ),
    ]
