# Generated by Django 5.2.4 on 2025-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_bookingdetail_taxi_bookingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxi",
            name="destination_cities",
            field=models.TextField(
                default=1,
                help_text="Enter multiple destination cities, separated by commas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxi",
            name="source_city",
            field=models.CharField(
                default=1, help_text="Enter the name of the source city", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxi",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("SEDAN", "Sedan"),
                    ("SEDAN_ETIOS", "Sedan Etios"),
                    ("MARUTI", "Maruti"),
                    ("SUZUKI", "Suzuki"),
                    ("SWIFT", "Swift"),
                    ("XUV", "XUV"),
                    ("INNOVA", "Innova"),
                    ("INNOVA_CRYSTA", "Innova Crysta"),
                    ("ERTIGA", "Ertiga"),
                    ("HYCROSS", "Hycross"),
                    ("TEMPO_16", "Tempo Traveler 16 Seater"),
                    ("TEMPO_18", "Tempo Traveler 18 Seater"),
                ],
                max_length=20,
            ),
        ),
    ]
