# Generated by Django 5.2.4 on 2025-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_taxi_destination_cities_taxi_source_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdetail",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="extra_hour_rate",
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="extra_km_rate",
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI Transfer"),
                    ("QR", "Scan QR Code"),
                    ("RAZORPAY", "Razorpay"),
                ],
                default="UPI",
                max_length=20,
            ),
        ),
    ]
