# Generated by Django 5.2.4 on 2025-08-02 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_bookingdetail_base_fare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("upi", "UPI Transfer"),
                    ("qr", "Scan QR Code"),
                    ("razorpay", "RazorPay"),
                ],
                default="upi",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="pickup_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
