# Generated by Django 5.2.4 on 2025-08-02 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_bookingrequest_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdetail",
            name="total_fare",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
