# Generated by Django 5.2.4 on 2025-08-02 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_bookingdetail_total_fare"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingdetail",
            name="pickup_datetime",
        ),
        migrations.AlterField(
            model_name="bookingdetail",
            name="gst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="bookingdetail",
            name="total_fare",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
            ),
        ),
    ]
