# Generated by Django 5.2.4 on 2025-08-02 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_remove_bookingdetail_pickup_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdetail",
            name="pickup_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_screenshots/"
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upi", "UPI Transfer"),
                    ("qr", "Scan QR Code"),
                    ("razorpay", "RazorPay"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
