# Generated by Django 5.2.4 on 2025-08-04 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_bookingdetail_pickup_datetime_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
