# Generated by Django 5.2.4 on 2025-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_delete_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="localrental",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localtransfer",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="oneway",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadtripbooking",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roundtrip",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
