# Generated by Django 5.2.4 on 2025-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_localrental_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxi",
            name="source_city",
            field=models.TextField(
                help_text="Enter multiple source cities, separated by commas"
            ),
        ),
    ]
