# Generated by Django 5.2.4 on 2025-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_taxi_source_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxi",
            name="source_city",
            field=models.CharField(
                help_text="Enter the name of the source city", max_length=100
            ),
        ),
    ]
