# Generated by Django 5.2.4 on 2025-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_alter_taxi_source_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxi",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("SEDAN", "Sedan"),
                    ("SEDAN_ETIOS", "Sedan Etios"),
                    ("MARUTI SUZUKI", "Maruti Suzuki"),
                    ("SWIFT", "Swift"),
                    ("XUV", "XUV"),
                    ("INNOVA", "Innova"),
                    ("INNOVA_CRYSTA", "Innova Crysta"),
                    ("ERTIGA", "Ertiga"),
                    ("HYCROSS", "Hycross"),
                    ("TEMPO_16", "Tempo Traveler 16 Seater"),
                    ("TEMPO_18", "Tempo Traveler 18 Seater"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="package_info",
            field=models.CharField(
                choices=[
                    ("Mini Ride - 4h/40km", "Mini Ride - 4h/40km"),
                    ("Half Day - 8h/80km", "Half Day - 8h/80km"),
                    ("Full Day - 12h/120km", "Full Day - 12h/120km"),
                    ("Custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
