# Generated by Django 5.2.4 on 2025-08-05 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_taxi_car_type_alter_taxi_package_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdetail",
            name="booking_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="full_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="mobile",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingdetail",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingdetail",
            name="package_name",
            field=models.CharField(
                choices=[
                    ("Mini Ride - 4h/40km", "Mini Ride - 4h/40km"),
                    ("Half Day - 8h/80km", "Half Day - 8h/80km"),
                    ("Full Day - 12h/120km", "Full Day - 12h/120km"),
                    ("Custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingdetail",
            name="payment_method",
            field=models.CharField(
                choices=[("UPI", "UPI Transfer"), ("QR", "Scan QR Code")],
                default="UPI",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("upi", "UPI Transfer"), ("qr", "Scan QR Code")],
                max_length=20,
                null=True,
            ),
        ),
    ]
