# Generated by Django 5.2.4 on 2025-08-05 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_bookingdetail_booking_id_bookingdetail_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdetail",
            name="booking_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
