# Generated by Django 5.2.4 on 2025-08-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_alter_bookingdetail_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdetail",
            name="taxi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.taxi",
            ),
        ),
        migrations.AddField(
            model_name="taxi",
            name="num_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taxi",
            name="total_rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
