# Generated by Django 5.2.4 on 2025-08-05 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_bookingdetail_taxi_taxi_num_ratings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="enquiry_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
