# Generated by Django 5.2.4 on 2025-08-05 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_enquiry_enquiry_id_enquiry_enquiry_sms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
