# Generated by Django 5.2.4 on 2025-08-05 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_alter_enquiry_enquiry_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VendorAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_mobile", models.CharField(max_length=15)),
                ("pickup_location", models.CharField(max_length=255)),
                ("drop_location", models.CharField(blank=True, max_length=255)),
                ("trip_date", models.DateField(default=django.utils.timezone.now)),
                ("vehicle_type", models.CharField(max_length=50)),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal or external booking reference",
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("allotted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="main.vendor",
                    ),
                ),
            ],
        ),
    ]
