# Generated by Django 5.2.4 on 2025-08-05 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_vendor_vendorallotment"),
    ]

    operations = [
        migrations.AddField(
            model_name="localrental",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="localrental",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="localtransfer",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="localtransfer",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oneway",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="oneway",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadtripbooking",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="roadtripbooking",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roundtrip",
            name="enquiry_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="roundtrip",
            name="enquiry_sms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
